version: '3.8'
services:
  database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - apps

networks:
  apps:
    external:
      name: apps
